name: build and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create src/environments/environment.ts file
        run: |
          mkdir -p src/environments
          touch src/environments/environment.ts
          echo "${{ secrets.firebaseConfig }}" >> src/environments/environment.ts

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.1

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build ./dist/angular-ledger/browser



